package com.joelcranston.numismatic_coins.trade;

import com.joelcranston.numismatic_coins.NumismaticCoins;
import com.joelcranston.numismatic_coins.config.Configs;
import net.minecraft.network.chat.Component;

/**
 * The built-in "Coin trades" data pack, which replaces vanilla's emerald trade pools with coin
 * trades for every profession and the wandering trader. Its data is generated by
 * {@code scripts/convert_trades.py}. The {@code villagerTrades} feature decides whether new worlds
 * start with it on; a world turns it on or off with {@code /datapack}.
 */
public final class CoinTrades {

    public static final String PACK_NAME = "coin_trades";

    private CoinTrades() {}

    public static void register() {

        ModLootFunctions.register();
        NumismaticCoins.xplat().registerBuiltinDataPack(PACK_NAME,
                Component.translatable("dataPack.numismatic_coins.coin_trades.name"),
                Configs.isFeatureEnabled("villagerTrades"));
    }
}
